name: Build Helix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions: 
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: helix-editor/helix
      
    - name: Set git config for long paths
      run: git config --system core.longpaths true
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Add WASM target
      run: rustup target add wasm32-wasi

    - name: Install C++ build tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Get latest commit
      shell: pwsh
      id: commit_message
      run: |
        $GIT_MESSAGE = git log -1 --pretty
        echo "GIT_MESSAGE=$GIT_MESSAGE" >> $env:GITHUB_ENV
        echo "GIT_MESSAGE=$GIT_MESSAGE" >> $env:GITHUB_OUTPUT
    
    - name: Run cargo
      run: cargo build --release --locked --target x86_64-pc-windows-msvc

    - name: Attest build provenance
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'target\x86_64-pc-windows-msvc\release\hx.exe'

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: helix
        path: target\x86_64-pc-windows-msvc\release\hx.exe

    - name: Set date
      id: set-date
      shell: pwsh
      run: |
        $CURRENT_DATE = Get-Date -UFormat "%Y.%m.%d"
        echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_ENV
        echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_OUTPUT
        
    - name: Update Nightly Current
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/auto-release')
      with:
        name: Nightly Build
        body: "${{ steps.commit_message.outputs.GIT_MESSAGE }}"
        tag_name: nightly
        prerelease: true
        files: |
          target/x86_64-pc-windows-msvc/release/hx.exe
